=== Relation f()Informatik vs. f()Mathematik
==== Darstellung
[source,javascript]
----
/* 
Mathematische Schreibweise
f(x) = 2x-1 
g:x -> 2x-1
*/

//Informatische Schreibweise
function f(x){
    return 2*x-1
}
let g = (x) => 2*x-1;
----

==== Grundmenge
Welche Menge soll einer Funktion von vornherein als Eingangswerte (Übergabeparameter) zur Verfügung stehen. Mathematisch spricht man hier von den *Grundmenge*

[NOTE]
====
Die Menge aller Eingangswerte, die grundsätzlich für die Variable x eingesetzt werden dürfen, heißt *Grundmenge* und wir mit G bezeichnet.
====

==== Definitionsmenge
[NOTE]
====
Die Menge aller Eingangswerte, die dann tatsächlich für x in die Funktion eingesetzt werden, heißt *Definitionsmenge* oder *Definitionsbereich* und wir mit D bezeichnet.
====

==== Wertemenge
Man kann alle Werte aus der Definitionsmenge für die Variable x in die Funktionsgleichung einsetzen und daraus jeweils den Funktionswert berechnen

.Andere Bezeichnung für Wertemenge
* Bildmenge
* Menge der Funktionswerte