== Beautiful-DnD

=== Links
https://www.youtube.com/watch?v=MYKwvGL1jU4&list=PLBguFN_KEgLimbYj8UgDmjKjLYalq63FQ&index=10[YOUTUBE] 



=== Sourcecode

.App.jsx
[source, javascript]
--
import React from 'react';
import { DragDropContext } from "react-beautiful-dnd";

function App() {
  const [user, setUser] = React.useState(db);
  const [state, setState] = React.useState([]);

  //Dieser useEffect aktualisiert mein state. Das bedeutet, wenn der User seine Auswahl ändert, wird dementsprechenden "Meine Auswahl" als State aktualisiert
  React.useEffect(() => {
    setState(() => { return user.columns["column-2"].taskIds });
  }, [user.columns["column-2"].taskIds]);


  // Achtung onDragEnd() ist in einem extra Abschnitt


  return (
    // Dies ist der Context, in dem sich die DragandDrop-Geschichte abspielen soll.
      // Die onDragEnd-Methode ist der Dreh und Angelpunkt der ganzen Ausführungslogik
    <DragDropContext onDragEnd={onDragEnd}>
      <div style={{ display: "flex" }}>

        {/* user kommen aus Datenbank */}
        {user.columnOrder.map(columnId => {
          const column = user.columns[columnId];
          const tasks = column.taskIds.map(taskId => user.tasks[taskId]);
          return (
            <Column key={column.id} column={column} tasks={tasks}
              style={{
                display: "flex", alignItems: "center", justifyContent: "center",
                padding: "1rem", boxShadow: "5px 5px 8px #888888",
                margin: "1rem", height: "10%", backgroundColor: "red"
              }} />
          )
        })}
      </div >
    </DragDropContext>
  );
}
--

.Column.jsx
[source, javascript]
--
import React from "react";
import Task from "./Task";
//Elternelement: Hier möchte ich etwas ablegen
import { Droppable } from "react-beautiful-dnd";

export default function Column({ column, tasks }) {
    return (
        <div style={{display: "flex", flexDirection: "column"}}>
            <div>
                {column.title}
            </div>
            <Droppable droppableId={column.id}>
                {provided => (
                    // Dieses <div> muss sein, sonst Probleme mit innerRef
                    <div>
                        <div
                            style={{minHeight: "100px"}}
                            ref={provided.innerRef}
                            {...provided.droppableProps}
                        >
                            {tasks.map((task, index) => {
                                return (<Task key={task.id} task={task} index={index} />);
                            })}
                            {provided.placeholder}
                        </div>
                    </div>
                )}
            </Droppable>
        </div>
    );
}
--

.Task.jsx
[source, javascript]
--
import React from "react";
// Kind-Element: Was möchte ich bewegen?
import { Draggable } from "react-beautiful-dnd";
export default function Task({ task, index }) {
    return (
        <Draggable draggableId={task.id} index={index}>
            {(provided) => (
                <Container 
                    {...provided.draggableProps}
                    {...provided.dragHandleProps}
                    ref={provided.innerRef}
                >
                    {` ${task.id}: ${task.vorname} ${task.nachname} `}
                </Container>
            )}
        </Draggable>
    )
}
--

.db.js
[source, javascript]
--
export const db = {
    tasks: {
        "task-1": { id: "task-1", vorname: "Hans", nachname: "Weber", image: "www.abc.musterhausen" },
        "task-2": { id: "task-2", vorname: "Günther", nachname: "Schmidt", image: "www.abc.musterhausen" },
        "task-3": { id: "task-3", vorname: "Eva", nachname: "Maier", image: "www.abc.musterhausen" },
    },

    columns: {
        "column-1": {
            id: "column-1",
            title: "Mitarbeiter",
            taskIds: ["task-1", "task-2", "task-3"]
        },
        "column-2": {
            id: "column-2",
            title: "Meine Auswahl",
            taskIds: []
        },
    },
    columnOrder: ["column-1", "column-2"],
}
--