== Drag and Drop
* https://www.youtube.com/watch?v=Q1PYQPK9TaM[Youtube]

=== Beautiful-DnD
==== Links
* https://www.youtube.com/watch?v=MYKwvGL1jU4&list=PLBguFN_KEgLimbYj8UgDmjKjLYalq63FQ&index=10[Youtube] 
* https://www.youtube.com/watch?v=mJLQVTBoWxg[Youtube]
* https://www.youtube.com/watch?v=Vqa9NMzF3wc[Youtube]
++++
<li style="margin-left: 24px; margin-bottom: 18px;"><a style="font-size: 1.0625rem;" ref="https://codesandbox.io/s/jovial-leakey-i0ex5?__cf_chl_jschl_tk__=972eb10fb3ad09853c82cb8ad3c19f445e764a7c-1601479490-0-ATy34oRS2fj6_RVjv6x58zyxfMm6bwWl9N8vlMgUyWFGIUfkwB5mWC9r4_Qf9ECtZ3fXjiKntEXI7VqPZjYXEaKCWyZlvJz1-W7QdFZMNCHlGjXaNHkUnq4DGpG1U8Oh2yqRZzwj7sAIR-z4camFnrOBiOaz1dVdn4as23v01ua6Zf1DBam_D2ki7d4G_2VIBWoE0ulN8RWimny5CwQw0-AIlapniWkS9I7in8nHf6ZlGErR1-nA2R3UR9N-aSixBbOiJtwm3WFEz0lipeYJP0EoJfRFaxWr6b_N0Jycs3ME&file=/src/App.js" target="_blank">Codebox - Basic</a></li>
++++
* https://codesandbox.io/s/simple-virtual-list-board-vgvzt[Codebox - Erweiterte Funktionalität]



==== Sourcecode

.onDragEnd.js
[source, javascript]
--
export const onDragEnd = (result, columns, setColumns) => {
  const { destination, source } = result;
  if (!destination) { return };

  if (source.droppableId !== destination.droppableId) {
    const sourceColumn = columns[source.droppableId];
    const destColumn = columns[destination.droppableId];
    const sourceTasks = [...sourceColumn.tasks];
    const destTasks = [...destColumn.tasks];
    const [removed] = sourceTasks.splice(source.index, 1);
    destTasks.splice(destination.index, 0, removed);
    setColumns({
      ...columns,
      [source.droppableId]: {
        ...sourceColumn,
        tasks: sourceTasks
      },
      [destination.droppableId]: {
        ...destColumn,
        tasks: destTasks
      }
    });
  } else {
    const column = columns[source.droppableId];
    const copiedTasks = [...column.tasks];
    const [removed] = copiedTasks.splice(source.index, 1);
    copiedTasks.splice(destination.index, 0, removed);
    setColumns({
      ...columns,
      [source.droppableId]: {
        ...column,
        tasks: copiedTasks
      }
    })
  }
}
--

.App.jsx
[source, javascript]
--
import React from 'react';
import { DragDropContext } from "react-beautiful-dnd";
import Column from "./Column";
import {onDragEnd} "./onDragEnd";
import {tasksDB} "./tasksDB";

const columnsFromBackend = {
  "column-1": {
    id: "column-1",
    title: "Mitarbeiter",
    tasks: tasksDB
  },
  "column-2": {
    id: "column-2",
    title: "Auswahl",
    tasks: []
  },
}

function App() {
  const [columns, setColumns] = React.useState(columnsFromBackend);
  const [state, setState] = React.useState([]);
  //Dieser useEffect aktualisiert mein state. Das bedeutet, wenn der User seine Auswahl ändert, wird dementsprechenden "Meine Auswahl" als State aktualisiert
  React.useEffect(() => {
    console.log(columns["column-2"].tasks);
    setState(columns["column-2"].tasks);
  }, [columns]);

  return (
    <DragDropContext onDragEnd={result => onDragEnd(result, columns, setColumns)}>
      <div style={{ display: "flex" }}>
        {Object.entries(columns).map(([id, column]) => {
          return (
            <Column key={id} column={column} tasks={tasks}
              style={{
                display: "flex", alignItems: "center", justifyContent: "center",
                padding: "1rem", boxShadow: "5px 5px 8px #888888",
                margin: "1rem", height: "10%", backgroundColor: "red"
              }} />
          )
        })}
      </div >
    </DragDropContext>
  );
}

export default App;
--

.Column.jsx
[source, javascript]
--
import React from "react";
import Task from "./Task";
import { Droppable } from "react-beautiful-dnd";
export default function Column({ column }) {
    return (
        <div style={{ display: "flex", flexDirection: "column" }}>
            <div>
                {column.title}
            </div>
            <Droppable droppableId={column.id}>
                {provided => (
                    // Dieses <div> muss sein, sonst Probleme mit innerRef
                    <div
                        {...provided.droppableProps}
                        ref={provided.innerRef}
                        style={{ minHeight: "100px" }}
                    >
                        {column.tasks.map((task, index) => {
                            return (<Task key={task.id} task={task} index={index} />);
                        })}
                        {provided.placeholder}
                    </div>
                )}
            </Droppable>
        </div>
    );
}
--

.Task.jsx
[source, javascript]
--
import React from "react";
import { Draggable } from "react-beautiful-dnd";

export default function Task({ task, index }) {
    return (
        <Draggable draggableId={task.id} index={index}>
            {(provided) => (
                <Container 
                    {...provided.draggableProps}
                    {...provided.dragHandleProps}
                    ref={provided.innerRef}
                >
                    {` ${task.id}: ${task.vorname} ${task.nachname} `}
                </Container>
            )}
        </Draggable>
    )

}
--

.tasksDB.js
[source, javascript]
--
export const tasks = [
  { id: "task-1", vorname: "Hans", nachname: "Weber", image: "www.spd.de" },
  { id: "task-2", vorname: "Günther", nachname: "Schmidt", image: "www.spd.de" },
  { id: "task-3", vorname: "Eva", nachname: "Maier", image: "www.spd.de" },
];
--

=== React DnD
==== Links
* https://www.youtube.com/watch?v=aK2PD_REk7A[Youtube]
